[profile.default]
src = "src"
out = "artifacts"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@account-abstraction/=node_modules/@account-abstraction/",
    "@iden3/=node_modules/@iden3/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solarity/=node_modules/@solarity/",
    "@uniswap/=node_modules/@uniswap/",
    "base64-sol/=node_modules/base64-sol/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "snarkjs/=node_modules/fixed-merkle-tree/node_modules/snarkjs/",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
